tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      rustup target add wasm32-unknown-unknown
      npm install -g near-cli
